---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-sa
  namespace: skillpulse
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::037302670171:role/secrets-role
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: skillpulse

spec:
  provider: aws
  parameters:
    region: "us-west-2"
    objects: |
      - objectName: "skillpulse-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: MYSQL_ROOT_PASSWORD
            objectAlias: MYSQL_ROOT_PASSWORD

          - path: MYSQL_DATABASE
            objectAlias: MYSQL_DATABASE

          - path: MYSQL_USER
            objectAlias: MYSQL_USER

          - path: MYSQL_PASSWORD
            objectAlias: MYSQL_PASSWORD

  secretObjects:
    - secretName: skillpulse-db
      type: Opaque

      data:
        - objectName: MYSQL_ROOT_PASSWORD
          key: MYSQL_ROOT_PASSWORD

        - objectName: MYSQL_DATABASE
          key: MYSQL_DATABASE

        - objectName: MYSQL_USER
          key: MYSQL_USER

        - objectName: MYSQL_PASSWORD
          key: MYSQL_PASSWORD